"""add hashed_password to users

Revision ID: 16275dc15c79
Revises: 02e0640492f3
Create Date: 2026-02-10 18:02:51.241764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16275dc15c79'
down_revision: Union[str, Sequence[str], None] = '02e0640492f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) nullable ekle
    op.add_column("users", sa.Column("hashed_password", sa.String(length=255), nullable=True))

    # 2) mevcut satırları doldur (geçici)
    op.execute("UPDATE users SET hashed_password = 'TEMP' WHERE hashed_password IS NULL")

    # 3) artık NOT NULL yap
    op.alter_column("users", "hashed_password", nullable=False)

def downgrade() -> None:
    op.drop_column("users", "hashed_password")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
