"""add uq users org_id email

Revision ID: 523675497f48
Revises: 16275dc15c79
Create Date: 2026-02-12 23:59:56.197799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523675497f48'
down_revision: Union[str, Sequence[str], None] = '16275dc15c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint(
        "uq_users_org_id_email",
        "users",
        ["org_id", "email"],
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "uq_users_org_id_email",
        "users",
        type_="unique",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
