"""add audit by fields

Revision ID: d2262546f632
Revises: f7e276086c91
Create Date: 2026-02-17 21:48:12.572089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2262546f632'
down_revision: Union[str, Sequence[str], None] = 'f7e276086c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('refresh_tokens', 'deleted_by')
    op.drop_column('refresh_tokens', 'updated_by')
    op.drop_column('refresh_tokens', 'created_by')
    op.drop_column('organizations', 'deleted_by')
    op.drop_column('organizations', 'updated_by')
    op.drop_column('organizations', 'created_by')
    # ### end Alembic commands ###
